### ISSUE TITLE
Not working in Belgium

### ISSUE THREAD

**Issue by quastorkev** [nandydark/NANDYBOMB#4]
Not working to all Belgian numbers (+32) 
0456: GSM. Range is owned by MobileViking
0460: GSM. Range is owned by Proximus
0465: GSM. Range is owned by Lycamobile
0467: GSM. Range is owned by Telenet
0468: GSM. Range is owned by Telenet
0470-: GSM. Range is owned by Proximus
0480-: GSM Range is owned by Telenet (Base)
0490-: GSM Range is owned by Orange

Only Vectone i can't test

**Comment by nandydark** [comment]
Okay whenever i have some free time... then i will fetch out some api's and add more support to this shit
